GET http://localhost:2001/player

###
GET http://localhost:2001/player/649a2cccd08b6b694351f0f8

###
POST http://localhost:2001/player
content-type: application/json

{
      "id": 5,
      "name": "Rafa",
      "email": "rafa@gail.com",
      "password": "Rafa"
}

###
DELETE  http://localhost:2001/player/649a2cccd08b6b694351f0f8